import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

/**
 * GET /api/configurations
 * List configurations
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Get current user
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const companyId = searchParams.get('company_id')
    const type = searchParams.get('type') as
      | 'model'
      | 'view'
      | 'workflow'
      | 'security'
      | 'report'
      | null
    const status = searchParams.get('status')

    // Check permissions
    const { data: profile } = await supabase
      .from('profiles')
      .select('role, company_id')
      .eq('id', user.id)
      .single()

    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 })
    }

    let query = supabase.from('configurations').select('*')

    // Filter by company (unless super_admin)
    if (companyId) {
      query = query.eq('company_id', companyId)
    } else if (profile.role !== 'super_admin') {
      query = query.eq('company_id', profile.company_id)
    }

    if (type) {
      query = query.eq('type', type)
    }

    if (status) {
      query = query.eq('status', status)
    }

    query = query.order('created_at', { ascending: false })

    const { data: configurations, error } = await query

    if (error) {
      throw new Error(error.message)
    }

    return NextResponse.json({ configurations })
  } catch (error: any) {
    console.error('[Configurations API] Error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

/**
 * POST /api/configurations
 * Create a new configuration (from template or AI)
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Get current user
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const {
      company_id,
      type,
      name,
      natural_language_input,
      requirements,
      template_id,
      variables,
    } = body

    if (!company_id || !type || !name) {
      return NextResponse.json(
        { error: 'company_id, type, and name are required' },
        { status: 400 }
      )
    }

    // Check permissions
    const { data: profile } = await supabase
      .from('profiles')
      .select('role, company_id')
      .eq('id', user.id)
      .single()

    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 })
    }

    if (profile.role !== 'super_admin' && profile.company_id !== company_id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    // If template_id is provided, apply template
    if (template_id) {
      const { getConfigurationTemplateService } = await import(
        '@/lib/services/configuration-template-service'
      )
      const templateService = getConfigurationTemplateService()
      const result = await templateService.applyTemplate(template_id, company_id, variables || {})

      return NextResponse.json(
        {
          configurationId: result.configurationId,
          generatedCode: result.generatedCode,
        },
        { status: 201 }
      )
    }

    // Otherwise, create empty configuration (will be generated by AI later)
    const { data: configuration, error: configError } = await supabase
      .from('configurations')
      .insert({
        company_id,
        type,
        name,
        natural_language_input,
        requirements,
        status: 'draft',
        created_by: user.id,
      })
      .select()
      .single()

    if (configError) {
      throw new Error(configError.message)
    }

    return NextResponse.json({ configuration }, { status: 201 })
  } catch (error: any) {
    console.error('[Configurations API] Error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

